### ISSUE TITLE
pkg-resources==0.0.0 in requirements.txt

### ISSUE THREAD

**Issue by jackieklaura** [feminist-python-meetup/name-tags#2]
On line 10 of the `requirements.txt` there is:
```
pkg-resources==0.0.0
```
When I wanted to install the requirements in my python3 virtualenv on a Ubuntu 18.04 system I got an error. So I just removed this line from the `requirements.txt` and everything went smoothly.

Now, doing a websearch, I found a [stackoverflow discussion this issue](https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command#40167445) and a [pip issue that says it is a bug in ubuntu](https://github.com/pypa/pip/issues/4022).

I'm not sure how this goes on other distros, but i suppos we should either remove the line or write a prominent heads-up note on this into the `README.md`?

**Comment by misspenalty** [comment]
It should work now, I removed the line from the `requirements.txt`!
